version: '3.8'

services:
  postgres:
    image: postgres
    container_name: local-postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: aman
      POSTGRES_PASSWORD: aman123
      POSTGRES_DB: management
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
